### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yichifauzi** [Jystro/Minecraft-info-bot#5]
Is possible just use player name expect from using uuid?

**Comment by Jystro** [comment]
Hey yichifauzi, no, with the current version it isn't possible to use the name instead of tje uuid. It is possible to use the uuid command to retrieve the uuid from the username and then pass it to the player command directly with some slight modifications. I'll be working on this issue as soon as possible and notify you when it will be implemented

**Comment by Jystro** [comment]
@yichifauzi your request has been implemented in [version 2.1.1](https://github.com/Jystro/Minecraft-info-bot/releases/tag/v2.1.1), you might want to check it out.
I'm closing the issue as it has been resolved. If you have any questions, feel free to create a new issue or reopen this one.
I hope this was helpful.
